### ISSUE TITLE
Spacebuild Error

### ISSUE THREAD

**Issue by Arch-Wizard** [spacebuild/spacebuild#143]
I'm having an issue with spacebuild 3 and for some reason it doesn't seem to include the shared.lua, I have tried to go though the files and find the problem couldn't find it don't know how to work. Of course i'm going to guess you know when the shared.lua isn't included it can't derive the gamemode sandbox. Common thing i'm noticing is that if I run it on a server is gets this issue but if i'm running it on single player then it works fine. Thank you for taking the time to read this.

>[Siper|3|STEAM_0:0:59497199] Lua Error:
Couldn't include file 'shared.lua' (File not found) (@addons/spacebuild/gamemodes/spacebuild/gamemode/cl_init.lua (line 9))
>[Siper|3|STEAM_0:0:59497199]Lua Error:
Filename: caf_tool_error, Message: CAF: Bad device catagory definition, `removing
![adb0d3c7a28f774f6116add11468cdce](https://user-images.githubusercontent.com/28636280/34528633-74d3a502-f077-11e7-84ed-1375def344dc.png)

**Comment by viral32111** [comment]
I fixed it by just deleting the gamemode folder inside the addon folder and creating a vanilla custom gamemode with no extra features just named spacebuild. Works the exact same and appears the same in the server browser just doesn't have errors.

**Comment by Arch-Wizard** [comment]
I've tried doing what you said and came up with this error instead, I double checked everything and even just rewrote the .txt file to something basic just to make sure but it still doesn't work. I don't understand why it just doesn't work when I set it to multiplayer
![7a33a7dbe7c0557285d4667703ccb7e5](https://user-images.githubusercontent.com/28636280/34642006-6bff6f14-f2da-11e7-9c53-875cce1fbb6b.png)

**Comment by viral32111** [comment]
I've never seen that error before. I'm guessing it can't find the gamemode. I've made a [repo](https://github.com/viral32111/spacebuild) for the gamemode I use on my servers, Extract it and drag it into `/garrysmod/gamemodes/` on your server. Make sure you have deleted the gamemode inside the addons folder and set it to run spacebuild in your command line.

**Comment by Arch-Wizard** [comment]
Thank you it works now, i'll try to see what I did wrong. Thank you again.

**Comment by viral32111** [comment]
No problem! Enjoy playing spacebuild :+1:
